"""add_sequence_column_to_sections

Revision ID: 1ef9fcff8a29
Revises: ec52a98da54f
Create Date: 2025-08-12 14:06:00.156565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ef9fcff8a29"
down_revision: Union[str, Sequence[str], None] = "ec52a98da54f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Custom commands to add sequence column and set existing values to 0
    op.add_column(
        "form_template_section",
        sa.Column("sequence", sa.Integer(), nullable=True, server_default="0"),
    )

    op.execute(
        "UPDATE form_template_section SET sequence = 1 WHERE id = 1"
    )  # Petitioner
    op.execute(
        "UPDATE form_template_section SET sequence = 2 WHERE id = 2"
    )  # Beneficiary
    op.execute(
        "UPDATE form_template_section SET sequence = 3 WHERE id = 3"
    )  # Translator

    op.alter_column("form_template_section", "sequence", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_template_section", "sequence")
    # ### end Alembic commands ###
