"""add form complete field to form

Revision ID: 973c3ab402d3
Revises: 3c92a05ed80d
Create Date: 2025-07-31 22:45:03.669034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "973c3ab402d3"
down_revision: Union[str, Sequence[str], None] = "3c92a05ed80d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form",
        sa.Column(
            "completed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column("form", sa.Column("completed_at", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form", "completed_at")
    op.drop_column("form", "completed")
    # ### end Alembic commands ###
