"""add_addl_fields_to_form_template_field

Revision ID: af789ae40efd
Revises: 1ef9fcff8a29
Create Date: 2025-08-12 14:14:31.739737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af789ae40efd"
down_revision: Union[str, Sequence[str], None] = "1ef9fcff8a29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "form_template_field",
        sa.Column("sequence", sa.Integer(), nullable=True, server_default="0"),
    )
    op.add_column(
        "form_template_field", sa.Column("key", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "form_template_field",
        sa.Column(
            "optional", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.add_column(
        "form_template_field",
        sa.Column("css_class", sa.String(length=255), nullable=True),
    )

    op.execute("UPDATE form_template_field SET key = name")
    op.execute("UPDATE form_template_field SET optional = false")

    # Use ROW_NUMBER() to automatically assign sequences within each section
    op.execute("""
        UPDATE form_template_field 
        SET sequence = subquery.row_num
        FROM (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY section_id 
                ORDER BY id
            ) as row_num
            FROM form_template_field
        ) subquery
        WHERE form_template_field.id = subquery.id
    """)

    op.alter_column("form_template_field", "sequence", nullable=False)
    op.alter_column("form_template_field", "key", nullable=False)
    op.alter_column("form_template_field", "optional", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_template_field", "css_class")
    op.drop_column("form_template_field", "optional")
    op.drop_column("form_template_field", "key")
    op.drop_column("form_template_field", "sequence")
    # ### end Alembic commands ###
