"""add form template field subtypes

Revision ID: 90f0b66c16f3
Revises: 27a2a41450ee
Create Date: 2025-09-16 12:26:50.775785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f0b66c16f3'
down_revision: Union[str, Sequence[str], None] = '27a2a41450ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_template_field', sa.Column('sub_type', sa.Enum('EMAIL', 'US_TELEPHONE', 'SSN', 'FEIN', 'NAICS_CODE', 'ZIP_CODE', 'US_STATE', name='formtemplatefieldsubtypes', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_template_field', 'sub_type')
    # ### end Alembic commands ###
