"""add workflow steps

Revision ID: 7a912ccb392c
Revises: c76c35f3b525
Create Date: 2025-09-10 17:18:05.772534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a912ccb392c"
down_revision: Union[str, Sequence[str], None] = "c76c35f3b525"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_step",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_step_id", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_step_id"],
            ["workflow_step.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_type_id"],
            ["project_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_workflow_step",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("workflow_step_id", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_step_id"],
            ["workflow_step.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("""
    INSERT INTO "public"."workflow_step" ("id", "project_type_id", "name", "key", "description", "parent_step_id", "sequence", "created_at", "updated_at") VALUES
        (1, 1, 'Document Gathering', 'H1B_DOCUMENT_GATHERING', 'Upload all required supporting documents for the H-1B petition', NULL, 1, '2025-09-10 17:26:12.21829-05', '2025-09-10 17:26:12.21829-05'),
        (2, 1, 'Information Collection', 'H1B_INFORMATION_COLLECTION', 'Gather beneficiary and employer details for the case', NULL, 2, '2025-09-10 17:26:12.231958-05', '2025-09-10 17:26:12.231958-05'),
        (3, 1, 'Wage Determination', 'H1B_WAGE_DETERMINATION', 'Assess prevailing wage requirements for the offered position', NULL, 3, '2025-09-10 17:26:12.245817-05', '2025-09-10 17:26:12.245817-05'),
        (4, 1, 'Determine ONET code', NULL, NULL, 3, 4, '2025-09-10 17:26:12.245817-05', '2025-09-10 17:26:12.245817-05'),
        (5, 1, 'Determine wage tiers for this location', NULL, NULL, 3, 5, '2025-09-10 17:26:12.260234-05', '2025-09-10 17:26:12.260234-05'),
        (6, 1, 'DOL Labor Certification', 'H1B_DOL_LABOR_CERTIFICATION', 'File the Labor Condition Application with the Department of Labor', NULL, 6, '2025-09-10 17:26:12.273391-05', '2025-09-10 17:26:12.273391-05'),
        (7, 1, 'Information Verification', NULL, 'Confirm accuracy of case details and supporting materials', 6, 7, '2025-09-10 17:26:12.273391-05', '2025-09-10 17:26:12.273391-05'),
        (8, 1, 'Attorney Review', NULL, 'Legal analysis and preparation of the LCA', 6, 8, '2025-09-10 17:26:12.28986-05', '2025-09-10 17:26:12.28986-05'),
        (9, 1, 'LCA Submission', NULL, 'File the LCA and ensure public posting compliance', 6, 9, '2025-09-10 17:26:12.302798-05', '2025-09-10 17:26:12.302798-05'),
        (10, 1, 'LCA Certification in Process', NULL, 'Await DOL adjudication of the LCA', 6, 10, '2025-09-10 17:26:12.312827-05', '2025-09-10 17:26:12.312827-05'),
        (11, 1, 'Petition Preparation', 'H1B_PETITION_PREPARATION', 'Assemble the complete USCIS petition package, including forms, supporting evidence, and attorney review', NULL, 11, '2025-09-10 17:26:12.322556-05', '2025-09-10 17:26:12.322556-05'),
        (12, 1, 'Information Verification', NULL, 'Validate final case data against LCA and USCIS requirements', 11, 12, '2025-09-10 17:26:12.322556-05', '2025-09-10 17:26:12.322556-05'),
        (13, 1, 'Attorney Initial Review', NULL, 'Comprehensive review of the USCIS petition package', 11, 13, '2025-09-10 17:26:12.331811-05', '2025-09-10 17:26:12.331811-05'),
        (14, 1, 'Employer Final Verification', NULL, 'Employer confirmation and signature of forms', 11, 14, '2025-09-10 17:26:12.340999-05', '2025-09-10 17:26:12.340999-05'),
        (15, 1, 'Attorney Final Review', NULL, 'Final legal check before filing', 11, 15, '2025-09-10 17:26:12.350197-05', '2025-09-10 17:26:12.350197-05'),
        (16, 1, 'USCIS Submission', 'H1B_USCIS_SUBMISSION', 'File the H-1B petition with USCIS and track the case through adjudication', NULL, 16, '2025-09-10 17:26:12.360682-05', '2025-09-10 17:26:12.360682-05'),
        (17, 1, 'Package Submitted', NULL, 'Petition filed with USCIS', 16, 17, '2025-09-10 17:26:12.360682-05', '2025-09-10 17:26:12.360682-05'),
        (18, 1, 'Receipt Notice Issued', NULL, 'USCIS receipt notice generated and shared with employer/beneficiary', 16, 18, '2025-09-10 17:26:12.370297-05', '2025-09-10 17:26:12.370297-05'),
        (19, 1, 'USCIS Adjudication Process', NULL, 'Petition under USCIS review and possible Requests for Evidence', 16, 19, '2025-09-10 17:26:12.379607-05', '2025-09-10 17:26:12.379607-05'),
        (20, 1, 'Final Decision', NULL, 'Approval or denial issued by USCIS', 16, 20, '2025-09-10 17:26:12.388699-05', '2025-09-10 17:26:12.388699-05');
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_workflow_step")
    op.drop_table("workflow_step")
    # ### end Alembic commands ###
