"""init user client and project table

Revision ID: d6d59a279019
Revises:
Create Date: 2025-07-30 12:42:50.454163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6d59a279019"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_public_id"), "client", ["public_id"], unique=True)
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "FAMILY_BASED_GREENCARD",
                "CITIZENSHIP",
                "EMPLOYMENT_BASED_GREENCARD",
                name="projecttype",
            ),
            nullable=False,
        ),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_client_id"), "project", ["client_id"], unique=False
    )
    op.create_index(op.f("ix_project_public_id"), "project", ["public_id"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_client_id"), "user", ["client_id"], unique=False)
    op.create_index(op.f("ix_user_public_id"), "user", ["public_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_public_id"), table_name="user")
    op.drop_index(op.f("ix_user_client_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_project_public_id"), table_name="project")
    op.drop_index(op.f("ix_project_client_id"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("ix_client_public_id"), table_name="client")
    op.drop_table("client")
    # ### end Alembic commands ###
