"""reversed fk relationship for client and user

Revision ID: 8bbd0c8595ab
Revises: 96777f01c3e9
Create Date: 2025-08-18 12:26:16.278614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8bbd0c8595ab"
down_revision: Union[str, Sequence[str], None] = "96777f01c3e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_client_user_id"), "client", ["user_id"], unique=False)
    op.create_foreign_key(None, "client", "user", ["user_id"], ["id"])
    op.add_column(
        "user",
        sa.Column(
            "role",
            sa.Enum("ADMINISTRATOR", "CLIENT", name="userrole", native_enum=False),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_user_client_id"), table_name="user")
    op.drop_constraint(op.f("user_client_id_fkey"), "user", type_="foreignkey")
    op.drop_column("user", "client_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("user_client_id_fkey"), "user", "client", ["client_id"], ["id"]
    )
    op.create_index(op.f("ix_user_client_id"), "user", ["client_id"], unique=False)
    op.drop_column("user", "role")
    op.drop_constraint(None, "client", type_="foreignkey")
    op.drop_index(op.f("ix_client_user_id"), table_name="client")
    op.drop_column("client", "user_id")
    # ### end Alembic commands ###
