"""update timestamp handling

Revision ID: e70e6f0d761e
Revises: 973c3ab402d3
Create Date: 2025-08-07 21:08:27.948586

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e70e6f0d761e"
down_revision: Union[str, Sequence[str], None] = "973c3ab402d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add server defaults to project timestamps
    op.execute("ALTER TABLE project ALTER COLUMN started_at SET DEFAULT now()")
    op.execute("ALTER TABLE project ALTER COLUMN updated_at SET DEFAULT now()")

    # Add server defaults to all other timestamp fields
    op.execute('ALTER TABLE "user" ALTER COLUMN created_at SET DEFAULT now()')
    op.execute('ALTER TABLE "user" ALTER COLUMN updated_at SET DEFAULT now()')

    op.execute("ALTER TABLE client ALTER COLUMN created_at SET DEFAULT now()")
    op.execute("ALTER TABLE client ALTER COLUMN updated_at SET DEFAULT now()")

    op.execute("ALTER TABLE form_template ALTER COLUMN created_at SET DEFAULT now()")
    op.execute("ALTER TABLE form_template ALTER COLUMN updated_at SET DEFAULT now()")

    op.execute(
        "ALTER TABLE form_template_section ALTER COLUMN created_at SET DEFAULT now()"
    )
    op.execute(
        "ALTER TABLE form_template_section ALTER COLUMN updated_at SET DEFAULT now()"
    )

    op.execute(
        "ALTER TABLE form_template_field ALTER COLUMN created_at SET DEFAULT now()"
    )
    op.execute(
        "ALTER TABLE form_template_field ALTER COLUMN updated_at SET DEFAULT now()"
    )

    op.execute(
        "ALTER TABLE form_template_field_option ALTER COLUMN created_at SET DEFAULT now()"
    )
    op.execute(
        "ALTER TABLE form_template_field_option ALTER COLUMN updated_at SET DEFAULT now()"
    )

    op.execute("ALTER TABLE form ALTER COLUMN created_at SET DEFAULT now()")
    op.execute("ALTER TABLE form ALTER COLUMN updated_at SET DEFAULT now()")

    op.execute(
        "ALTER TABLE form_field_response ALTER COLUMN created_at SET DEFAULT now()"
    )
    op.execute(
        "ALTER TABLE form_field_response ALTER COLUMN updated_at SET DEFAULT now()"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove server defaults from project timestamps
    op.execute("ALTER TABLE project ALTER COLUMN started_at DROP DEFAULT")
    op.execute("ALTER TABLE project ALTER COLUMN updated_at DROP DEFAULT")

    # Remove server defaults from all other timestamp fields
    op.execute('ALTER TABLE "user" ALTER COLUMN created_at DROP DEFAULT')
    op.execute('ALTER TABLE "user" ALTER COLUMN updated_at DROP DEFAULT')

    op.execute("ALTER TABLE client ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE client ALTER COLUMN updated_at DROP DEFAULT")

    op.execute("ALTER TABLE form_template ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE form_template ALTER COLUMN updated_at DROP DEFAULT")

    op.execute("ALTER TABLE form_template_section ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE form_template_section ALTER COLUMN updated_at DROP DEFAULT")

    op.execute("ALTER TABLE form_template_field ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE form_template_field ALTER COLUMN updated_at DROP DEFAULT")

    op.execute(
        "ALTER TABLE form_template_field_option ALTER COLUMN created_at DROP DEFAULT"
    )
    op.execute(
        "ALTER TABLE form_template_field_option ALTER COLUMN updated_at DROP DEFAULT"
    )

    op.execute("ALTER TABLE form ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE form ALTER COLUMN updated_at DROP DEFAULT")

    op.execute("ALTER TABLE form_field_response ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE form_field_response ALTER COLUMN updated_at DROP DEFAULT")

    # ### end Alembic commands ###
