"""extended client properties

Revision ID: 1f05a3c02ee3
Revises: 1dc21530c447
Create Date: 2025-09-04 12:05:20.055564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f05a3c02ee3"
down_revision: Union[str, Sequence[str], None] = "1dc21530c447"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client", sa.Column("trade_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "client", sa.Column("first_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "client", sa.Column("last_name", sa.String(length=255), nullable=True)
    )
    op.add_column("client", sa.Column("address", sa.String(length=255), nullable=True))
    op.add_column("client", sa.Column("address2", sa.String(length=255), nullable=True))
    op.add_column("client", sa.Column("city", sa.String(length=255), nullable=True))
    op.add_column("client", sa.Column("state", sa.String(length=255), nullable=True))
    op.add_column("client", sa.Column("zip", sa.String(length=255), nullable=True))
    op.add_column(
        "client", sa.Column("telephone", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "client", sa.Column("naics_code", sa.String(length=255), nullable=True)
    )
    op.add_column("client", sa.Column("fein", sa.String(length=255), nullable=True))

    op.execute("UPDATE client SET first_name = '' where first_name is null")
    op.execute("UPDATE client SET last_name = '' where last_name is null")
    op.execute("UPDATE client SET address = '' where address is null")
    op.execute("UPDATE client SET city = '' where city is null")
    op.execute("UPDATE client SET state = '' where state is null")
    op.execute("UPDATE client SET zip = '' where zip is null")
    op.execute("UPDATE client SET telephone = '' where telephone is null")
    op.execute("UPDATE client SET naics_code = '' where naics_code is null")
    op.execute("UPDATE client SET fein = '' where fein is null")

    op.alter_column("client", "first_name", nullable=False)
    op.alter_column("client", "last_name", nullable=False)
    op.alter_column("client", "address", nullable=False)
    op.alter_column("client", "city", nullable=False)
    op.alter_column("client", "state", nullable=False)
    op.alter_column("client", "zip", nullable=False)
    op.alter_column("client", "telephone", nullable=False)
    op.alter_column("client", "naics_code", nullable=False)
    op.alter_column("client", "fein", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "fein")
    op.drop_column("client", "naics_code")
    op.drop_column("client", "telephone")
    op.drop_column("client", "zip")
    op.drop_column("client", "state")
    op.drop_column("client", "city")
    op.drop_column("client", "address2")
    op.drop_column("client", "address")
    op.drop_column("client", "last_name")
    op.drop_column("client", "first_name")
    op.drop_column("client", "trade_name")
    # ### end Alembic commands ###
