"""add icon to workflow step

Revision ID: 27a2a41450ee
Revises: 7a912ccb392c
Create Date: 2025-09-16 11:27:09.052281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27a2a41450ee"
down_revision: Union[str, Sequence[str], None] = "7a912ccb392c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_step", sa.Column("icon", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###

    op.execute(
        "UPDATE workflow_step SET icon = 'FileText' WHERE key = 'H1B_DOCUMENT_GATHERING'"
    )
    op.execute(
        "UPDATE workflow_step SET icon = 'NotepadText' WHERE key = 'H1B_INFORMATION_COLLECTION'"
    )
    op.execute(
        "UPDATE workflow_step SET icon = 'DollarSign' WHERE key = 'H1B_WAGE_DETERMINATION'"
    )
    op.execute(
        "UPDATE workflow_step SET icon = 'CircleCheck' WHERE key = 'H1B_DOL_LABOR_CERTIFICATION'"
    )
    op.execute(
        "UPDATE workflow_step SET icon = 'ClipboardPen' WHERE key = 'H1B_PETITION_PREPARATION'"
    )
    op.execute(
        "UPDATE workflow_step SET icon = 'Send' WHERE key = 'H1B_USCIS_SUBMISSION'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_step", "key", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("workflow_step", "icon")
    # ### end Alembic commands ###
