"""fix project form cascade error

Revision ID: 3c92a05ed80d
Revises: 5312079336a5
Create Date: 2025-07-31 21:16:29.883561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c92a05ed80d"
down_revision: Union[str, Sequence[str], None] = "5312079336a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("form_project_id_fkey"), "form", type_="foreignkey")
    op.create_foreign_key(
        None, "form", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("form_field_response_form_template_field_id_fkey"),
        "form_field_response",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("form_field_response_form_id_fkey"),
        "form_field_response",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "form_field_response", "form", ["form_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "form_field_response",
        "form_template_field",
        ["form_template_field_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "form_field_response", type_="foreignkey")
    op.drop_constraint(None, "form_field_response", type_="foreignkey")
    op.create_foreign_key(
        op.f("form_field_response_form_id_fkey"),
        "form_field_response",
        "form",
        ["form_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("form_field_response_form_template_field_id_fkey"),
        "form_field_response",
        "form_template_field",
        ["form_template_field_id"],
        ["id"],
    )
    op.drop_constraint(None, "form", type_="foreignkey")
    op.create_foreign_key(
        op.f("form_project_id_fkey"), "form", "project", ["project_id"], ["id"]
    )
    # ### end Alembic commands ###
